resources:
- ../../../../../templates/rootSyncs/git/ns/
- ../../../../../templates/rootSyncs/git/add-ons/

# nameSuffix: -pv-idv-caas-01-cluster-1

patches:
- target:
    kind: RootSync
    name: ns-vending
  patch: |-
    - op: replace
      path: /spec/git/dir
      value: envs/dev/

- target:
    kind: RootSync
    name: add-ons
  patch: |-
    - op: replace
      path: /spec/git/dir
      value: caas/dev/cluster-1
    - op: replace
      path: /spec/git/branch
      value: main