resources:
- ../../../../rootSyncs/git/ns/

patches:
- target:
    kind: RootSync
    name: namespace-vending
  patch: |-
    - op: replace
      path: /metadata/name
      value: istio-acm-cluster-1-ns
    - op: replace
      path: /metadata/annotations/configsync.gke.io~1cluster-name-selector
      value: istio-acm-cluster-1