resources:
- ../../../../templates/rootSyncs/git/ns/
- ../../../../templates/rootSyncs/git/add-ons/

patches:
- target:
    kind: RootSync
    name: namespace-vending
  patch: |-
    - op: replace
      path: /metadata/name
      value: istio-acm-cluster-1-ns
    - op: replace
      path: /spec/git/dir
      value: envs/dev/caas/cluster-1
    - op: replace
      path: /metadata/annotations/configsync.gke.io~1cluster-name-selector
      value: istio-acm-cluster-1

- target:
    kind: RootSync
    name: add-ons
  patch: |-
    - op: replace
      path: /metadata/name
      value: istio-acm-cluster-1-add-ons
    - op: replace
      path: /spec/git/dir
      value: caas/dev
    - op: replace
      path: /metadata/annotations/configsync.gke.io~1cluster-name-selector
      value: istio-acm-cluster-1