apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: ns-vending
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: "https://github.com/lbg-cloud-platform/cls_ple_gcp_gke_stratos_shared_root_acm"
    revision: "HEAD"
    branch: "main"
    dir: ""
    auth: token
    secretRef:
      name: git-creds